################################################################################
# Logitech-Media-Server aka Slimserver
################################################################################
version: "3.7"

services:
  logitech-media-server:
    container_name: lms
    image: doliana/logitech-media-server:latest-7.9.3
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    volumes:
      # folder where lms stores its data (cache, logs, prefs)
      - <LMS_PERSISTENT_DIR>:/srv/squeezebox
      # folder where lms should look for music
      - <MUSIC_LIBRARY>:/srv/music
      # use time of host
      - /etc/localtime:/etc/localtime:ro
      # use timezone of host
      - /etc/timezone:/etc/timezone:ro
